#!/bin/bash
dir=$1
cd $dir
touch "54 Dole Hlavou:Horkyze Slize-Silny Refren.mp3" 
touch "Corrida: Kabat-Kostlivci.ogg"
touch "adfafaffaf.dfs"
touch "tosemnepatri.csv"
touch "Hybrid Theory:Linkin Park-In The End.mp3"
touch "Meteora: Linkin Park-Breaking The Habit.mp3"
touch "Hybrid Theory:Linkin Park-Forgotten.wav"
touch "Meteora:Linkin Park-Numb.ogg"
touch "mp3alenenitoono.docx"
touch "54 Dole Hlavou:Horkyze Slize-Liza A Wendy.wav"
touch "Proffesional Rapper: LilDicky - Save That Money.ogg"
touch "fafafafafafaf"
touch "Proffesional Rapper: Lil Dicky - Molly.wav"
